## Getting Started
### Tensors
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import numpy as np
import torch

In [2]:
# construct 2D empty matrix
x= torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [4]:
# construct a randomly initialised matrix
x= torch.rand(5,3)
print(x)
print(type(x))

tensor([[0.1832, 0.7748, 0.9579],
        [0.6598, 0.4010, 0.5804],
        [0.0334, 0.1353, 0.7693],
        [0.0082, 0.2482, 0.7219],
        [0.0736, 0.3785, 0.6435]])
<class 'torch.Tensor'>


In [6]:
x= torch.zeros(5,3)
print(x)
print(type(x))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [7]:
x= torch.zeros(5,3, dtype= torch.long)
print(x)
print(type(x))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
<class 'torch.Tensor'>


Construct a tensor directly from data:

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor:

In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [25]:
Y= torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]), dtype= torch.int32)
print(y)
print(type(x))
print(x.dtype)

# by default tensor.dtype is same as the dtype of data

tensor([[ 0.6062,  0.2490, -1.2526],
        [-0.0202, -0.6882,  0.0204],
        [-1.2667, -0.5891,  0.2721],
        [-1.2246,  1.3880, -1.4621],
        [ 1.3381,  1.4288,  0.5598]])
<class 'torch.Tensor'>
torch.float32


## Class tensor:
#### There are a few ways for creating Tensors depending upon your purpose.
-  To create a tensor from previously existing data: tensor.torch()
-  To create a tensor of similar size and similar dtype: tensor.*_like()
-  To create a tensor with siilar type but different size as another tensor: tensor.new_*

new_tensor: <br>
- Returns a new Tensor with data as the tensor data. By default the Tensor has the same tensor.dtype as this tensor

In [26]:
x = x.new_ones(5, 3, dtype=torch.double)      
print(x)

x = torch.randn_like(x, dtype=torch.float) 
print(x) 

print(x.size())
# torch.Size is a tuple, so it supports all tuple operations.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1896,  0.1790, -0.4507],
        [ 1.1416,  1.9149, -0.1642],
        [-1.2786, -1.2138, -0.2509],
        [-0.0091, -0.4977, -0.0211],
        [-1.6002,  0.9527,  0.9755]])
torch.Size([5, 3])


new_empty(size, dtype=None, device=None, requires_grad=False) → Tensor: <br>
- Returns a tensor of same size filled with unitialised data. By default the returned tensor has same dtype as this tensor
<br>

new_ones(size, dtype=None, device=None, requires_grad=False) → Tensor: <br>
- Returns a Tensor of size size filled with 1. By default, the returned Tensor has the same torch.dtype  as this tensor.<br>

new_zeros(size, dtype=None, device=None, requires_grad=False) → Tensor: <br>
- Returns a Tensor of size size filled with 0. By default, the returned Tensor has the same torch.dtype  as this tensor.



### Operations
There are multiple syntaxes for operations. 

In [13]:
# Addition syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6062,  0.2490, -1.2526],
        [-0.0202, -0.6882,  0.0204],
        [-1.2667, -0.5891,  0.2721],
        [-1.2246,  1.3880, -1.4621],
        [ 1.3381,  1.4288,  0.5598]])


In [16]:
# Addition: syntax 2
print(torch.add(x, y))
print(type(torch.add(x, y)))

# torch.add returns an object of class torch.Tensor

tensor([[ 0.6062,  0.2490, -1.2526],
        [-0.0202, -0.6882,  0.0204],
        [-1.2667, -0.5891,  0.2721],
        [-1.2246,  1.3880, -1.4621],
        [ 1.3381,  1.4288,  0.5598]])
<class 'torch.Tensor'>


In [17]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6062,  0.2490, -1.2526],
        [-0.0202, -0.6882,  0.0204],
        [-1.2667, -0.5891,  0.2721],
        [-1.2246,  1.3880, -1.4621],
        [ 1.3381,  1.4288,  0.5598]])


In [18]:
# Addition: in-place
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6062,  0.2490, -1.2526],
        [-0.0202, -0.6882,  0.0204],
        [-1.2667, -0.5891,  0.2721],
        [-1.2246,  1.3880, -1.4621],
        [ 1.3381,  1.4288,  0.5598]])


Similarly y.copy_(x): copies y to x and 
y.t_() changes y

You can use standard NumPy like extension for indicing, sclicing, etc

In [19]:
print(x[:, 1])

tensor([-0.4853, -1.1220, -0.7902,  0.7715,  1.3365])


Resizing: If you want to resize/reshape tensor, you can use torch.view: <br>
Use torch.Tensor.item() to get a Python number from a tensor containing a single value:


In [39]:
x = torch.tensor([[1]])
print(x)
x.item()

tensor([[1]])


1

## NumPy Bridge
### Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

#### Converting a Torch Tensor to a NumPy Array

In [40]:
a = torch.ones(5)
print(a)
print(type(a))
b= a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [41]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [42]:
a = np.ones(5)
print(type(a))
b = torch.from_numpy(a)
print(b)
print(type(b))
np.add(a, 1, out=a)
print(a)
print(b)

<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors